workspace:
  base: /go
  path: src

clone:
  git:
    image: plugins/git:next
    depth: 50
    tags: true

pipeline:
  lint:
    image: hadolint/hadolint:latest-debian
    pull: true
    commands:
      - hadolint Dockerfile
    when:
      event:
        - push
        - pull_request
      branch:
        - master
  
  docker-latest:
    image: plugins/docker:17.12
    secrets: [ docker_username, docker_password ]
    pull: true
    repo: zzdats/sonar-scanner-cli
    cache_from: zzdats/sonar-scanner-cli
    tag:
      - latest
    when:
      event:
        - push
      branch:
        - master

  docker-version:
    image: plugins/docker:17.12
    secrets: [ docker_username, docker_password ]
    pull: true
    repo: zzdats/sonar-scanner-cli
    cache_from: zzdats/sonar-scanner-cli
    auto_tag: true
    when:
      event:
        - tag
